# Use container based infrastructure
sudo: false

language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install --quiet -r requirements.txt
  # Separate the coveralls package because it is only a test requirement
  - pip install --quiet coveralls

script:
  - nosetests --with-coverage --cover-package=legofy
  - python setup.py install
  - legofy tests/before/flower.jpg flower_lego.png

after_success:
  - coveralls
